Traceback (most recent call last):
  File "mongodemo.py", line 165, in <module>
    loss.backward()
  File "/data/users2/washbee/anaconda3/envs/neurips/lib/python3.8/site-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "/data/users2/washbee/anaconda3/envs/neurips/lib/python3.8/site-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 6.50 GiB (GPU 0; 31.74 GiB total capacity; 26.50 GiB already allocated; 2.29 GiB free; 28.32 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/data/users2/washbee/anaconda3/envs/neurips/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/data/users2/washbee/anaconda3/envs/neurips/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/data/users2/washbee/anaconda3/envs/neurips/lib/python3.8/site-packages/torch/utils/data/_utils/pin_memory.py", line 51, in _pin_memory_loop
    do_one_step()
  File "/data/users2/washbee/anaconda3/envs/neurips/lib/python3.8/site-packages/torch/utils/data/_utils/pin_memory.py", line 28, in do_one_step
    r = in_queue.get(timeout=MP_STATUS_CHECK_INTERVAL)
  File "/data/users2/washbee/anaconda3/envs/neurips/lib/python3.8/multiprocessing/queues.py", line 116, in get
    return _ForkingPickler.loads(res)
  File "/data/users2/washbee/anaconda3/envs/neurips/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 307, in rebuild_storage_fd
    fd = df.detach()
  File "/data/users2/washbee/anaconda3/envs/neurips/lib/python3.8/multiprocessing/resource_sharer.py", line 57, in detach
